default_stages: [pre-commit, pre-push]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: trailing-whitespace
        exclude: '\.json$'
      - id: end-of-file-fixer
      - id: check-merge-conflict
        args: [--assume-in-merge]
